import {
  IRecommendedBootstrapAccountHeaderDto,
  IRecommendedBootstrapDto,
} from '@app/ledger/dtos/recommended-bootstrap/recommended-bootstrap.dto';

const receivables: IRecommendedBootstrapAccountHeaderDto[] = [
  {
    key: 'trade-receivables',
    name: 'Trade Receivables',
    type: 'asset',
    subType: 'receivables',
    behavior: 'trade_receivable',
    isControlAccount: true,
    controlAccountCode: '102000',
    sub: [],
  },
  {
    key: 'statutory-receivables',
    name: 'Statutory Receivables',
    type: 'asset',
    subType: 'receivables',
    behavior: 'statutory_receivable',
    isControlAccount: true,
    controlAccountCode: '102000',
    sub: [
      {
        key: 'statutory-receivables-default',
        name: 'Statutory Receivables (Default)',
        type: 'asset',
        subType: 'receivables',
        behavior: 'statutory_receivable',
        isControlAccount: false,
        controlAccountKey: 'statutory-receivables',
      },
    ],
  },
];

const payables: IRecommendedBootstrapAccountHeaderDto[] = [
  {
    key: 'trade-payables',
    name: 'Trade Payables',
    type: 'liability',
    subType: 'payable',
    behavior: 'trade_payable',
    isControlAccount: true,
    controlAccountCode: '201000',
    meta: null,
    sub: [],
  },
  {
    key: 'statutory-payables',
    name: 'Statutory Payables',
    type: 'liability',
    subType: 'payable',
    behavior: 'tax_payable',
    isControlAccount: true,
    controlAccountCode: '201000',
    meta: null,
    sub: [
      {
        key: 'statutory-payables-default',
        name: 'Statutory Payables (Default)',
        type: 'liability',
        subType: 'payable',
        behavior: 'tax_payable',
        isControlAccount: false,
        controlAccountKey: 'statutory-payables',
        meta: null,
      },
    ],
  },
];

const revenue: IRecommendedBootstrapAccountHeaderDto[] = [
  {
    key: 'services-default',
    name: 'Services (Default)',
    type: 'revenue',
    subType: 'services',
    behavior: 'services',
    isControlAccount: false,
    controlAccountCode: '401000',
    sub: [],
  },
  {
    key: 'employment-income-default',
    name: 'Employment Income (Default)',
    type: 'revenue',
    subType: 'employment_income',
    behavior: 'employment_income',
    isControlAccount: false,
    controlAccountCode: '403000',
    sub: [],
  },
  {
    key: 'gain-on-sale-of-assets-default',
    name: 'Gain on Sale of Assets (Default)',
    type: 'revenue',
    subType: 'gain_on_asset_sale',
    behavior: 'gain_on_asset_sale',
    isControlAccount: false,
    controlAccountCode: '405000',
    sub: [],
  },
  {
    key: 'unrealized-gains-default',
    name: 'Unrealized Gains (Default)',
    type: 'revenue',
    subType: 'unrealized_gains',
    behavior: 'unrealized_gains',
    isControlAccount: false,
    controlAccountCode: '406000',
    sub: [],
  },
  {
    key: 'grants-default',
    name: 'Grants (Default)',
    type: 'revenue',
    subType: 'grants',
    behavior: 'grants',
    isControlAccount: false,
    controlAccountCode: '407000',
    sub: [],
  },
  {
    key: 'gifts-default',
    name: 'Gifts (Default)',
    type: 'revenue',
    subType: 'gifts',
    behavior: 'gifts',
    isControlAccount: false,
    controlAccountCode: '408000',
    sub: [],
  },
];

const expense: IRecommendedBootstrapAccountHeaderDto[] = [
  {
    key: 'direct-costs-default',
    name: 'Direct Costs (Default)',
    type: 'expense',
    subType: 'direct_costs',
    behavior: 'default_direct_cost',
    isControlAccount: false,
    controlAccountCode: '500000',
    sub: [],
  },
  {
    key: 'rent-and-utilities-default',
    name: 'Rent and Utilities (Default)',
    type: 'expense',
    subType: 'rent_and_utilities',
    behavior: 'rent_and_utilities',
    isControlAccount: false,
    controlAccountCode: '502000',
    sub: [],
  },
  {
    key: 'bank-charge-default',
    name: 'Bank Charge (Default)',
    type: 'expense',
    subType: 'bank_charge',
    behavior: 'bank_charge',
    isControlAccount: false,
    controlAccountCode: '507000',
    sub: [],
  },
  {
    key: 'finance-cost-default',
    name: 'Finance Cost (Default)',
    type: 'expense',
    subType: 'finance_cost',
    behavior: 'finance_cost',
    isControlAccount: false,
    controlAccountCode: '508000',
    sub: [],
  },
  {
    key: 'interest-default',
    name: 'Interest (Default)',
    type: 'expense',
    subType: 'interest',
    behavior: 'interest',
    isControlAccount: false,
    controlAccountCode: '509000',
    sub: [],
  },
  {
    key: 'tax-expense-default',
    name: 'Tax Expense (Default)',
    type: 'expense',
    subType: 'income_tax_expense',
    behavior: 'tax_expense',
    isControlAccount: false,
    controlAccountCode: '510000',
    sub: [],
  },
  {
    key: 'unrealized-loss-default',
    name: 'Unrealized Loss (Default)',
    type: 'expense',
    subType: 'unrealized_loss',
    behavior: 'unrealized_loss',
    isControlAccount: false,
    controlAccountCode: '511000',
    sub: [],
  },
  {
    key: 'asset-disposal-loss-default',
    name: 'Asset Disposal Loss (Default)',
    type: 'expense',
    subType: 'loss_on_asset_disposal',
    behavior: 'asset_disposal_loss',
    isControlAccount: false,
    controlAccountCode: '512000',
    sub: [],
  },
];

const suspense: IRecommendedBootstrapAccountHeaderDto[] = [
  {
    key: 'asset-suspense-account',
    name: 'Asset Suspense Account',
    type: 'asset',
    subType: 'suspense',
    behavior: 'default',
    isControlAccount: false,
    sub: [],
  },
  {
    key: 'liability-suspense-account',
    name: 'Liability Suspense Account',
    type: 'liability',
    subType: 'suspense',
    behavior: 'default',
    isControlAccount: false,
    sub: [],
  },
];

export default function makeGetRecommendedBootstrapUsecase() {
  return (): IRecommendedBootstrapDto => {
    return { receivables, payables, revenue, expense, suspense };
  };
}
